### ISSUE TITLE
Create backup of reminder data

### ISSUE THREAD

**Issue by davidwygant** [mpdifran/Memento-Issues#16]
If I lose my iPhone, is my data stored in the cloud so that I can access again? If not, can you please enable, e.g., login.

**Comment by mpdifran** [comment]
Thanks for the feature request! Since the app uses Apple reminders database, your reminders are stored in iCloud if you've turned on iCloud for your reminders (similar for reminders attached to external calendars). It'd be tricky for me to factor in my own backup service, so I recommend using the ones already available!
