### ISSUE TITLE
Reordering lists

### ISSUE THREAD

**Issue by Sydneyeditor1** [mpdifran/Memento-Issues#48]
**Info:**
 Device: Iphone 12
 OS: 14.71.1
 Memento Version 3.4.3 (21)

**Describe the bug**
How do I reorder lists/ reminders. I want Today at the top and the rest of the week and then future ones last? 

It would also be really nice to have an option to contact support without having to sign up for an account here, and lodge a bug. I'm not a coder, but I do need clearer help instructions only. 

**Expected behavior**
Lists to be reordered the way I want.

**Comment by mpdifran** [comment]
Thanks for the bug report!

I decided to use GitHub to manage bugs to make it easier for me to track when I begin working on it, and give you more visibility as well since it's just me working on the project (you can see what I'm working on here https://github.com/mpdifran/Memento-Issues/projects/1).

In order to reorder lists, you just need to go to the lists tab, and tap edit. You can reorder them there.

As for ordering reminders, I believe there is a feature request to sort them automatically, but for now the reminders need to be ordered by you manually. They can be rearranged by long pressing on them and dragging them to the new spot.

The For you tab might have what your looking for in terms of ordering by alarm date. You can also filter down the lists that appear there.

**Comment by Sydneyeditor1** [comment]
Thanks for your help. I couldn't see these details in the instructions anywhere.
